### ISSUE TITLE
The algorithm used here is not correct for all inputs

### ISSUE THREAD

**Issue by semisight** [mbaersch/get-root-domain#1]
https://github.com/mbaersch/get-root-domain/blob/d316df624417f3027b1de216572ab9fe6ebcf208/template.tpl#L60

As pointed out in the Github gist linked in the code above, this will fail for `https://www.mesdroitssociaux.gouv.fr/accueil/`. The correct result here should be `mesdroitssociaux.gouv.fr'.

**Comment by mbaersch** [comment]
That´s true. Let me add the obvoius comment that no (simple) RegEx will ever catch all cases without a lot of "if-stuff"... or a list like mentioned in the comment from the comments in the linked Gist.

I do not see how to solve this without adding some kind of ugly "patch" here. If you know a better solution, feel free to contribute. I would not dare to mess around with this RegEx because I am sure it would break things.

**Comment by mbaersch** [comment]
maybe you want to give https://github.com/analytics-debugger/gtm-template-root-domain-variable a try. It uses a different approach and verifies the result by setting a test cookie. I like the idea but using cookies can be a problem on the other hand...

**Comment by semisight** [comment]
We talked it over and we think there's value in the template even with the caveat above. Personally, I think it would be great to note somewhere that this is a potential pitfall, but I will leave it up to you.
